/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lowlevel_LedNative */

#ifndef _Included_com_example_lowlevel_LedNative
#define _Included_com_example_lowlevel_LedNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lowlevel_LedNative
 * Method:    openDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lowlevel_LedNative_openDev
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lowlevel_LedNative
 * Method:    closeDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lowlevel_LedNative_closeDev
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lowlevel_LedNative
 * Method:    devOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lowlevel_LedNative_devOn
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lowlevel_LedNative
 * Method:    devOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lowlevel_LedNative_devOff
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
